from __future__ import print_function
import tensorflow as tf
import numpy as np

from datetime import date
print(date.today())

print(tf.__version__)
print(np.__version__)

print('tf.add')
print('tf.substract')
print('tf.multiply')
print('tf.scalar_mul')
print('tf.div')
print('tf.truediv')
print('tf.mod')
print('tf.cross')
print('tf.add_n')
print('tf.abs')
print('tf.negative')
print('tf.sign')
print('tf.reciprocal')
print('tf.square')
print('tf.round')
print('tf.floor')
print('tf.ceil')
print('tf.sqrt')
print('tf.rsqrt')
print('tf.pow')
print('tf.log')
print('tf.maximum')
print('tf.where')
print('tf.minimum')
print('tf.sin')
print('tf.cos')
print('tf.tan')
print('tf.squared_difference')

print('tf.diag')
print('tf.diag_part')
print('tf.transpose')
print('tf.eye')
print('tf.matrix_diag')
print('tf.matrix_transpose')
print('tf.matmul')
print('tf.matrix_determinant')
print('tf.matrix_inverse')
print('tf.cholesky')
print('tf.self_adjoint_eig')
print('tf.svd')
print('tf.reduce_sum')
print('tf.reduce_prod')
print('tf.reduce_min')
print('tf.reduce_max')
print('tf.reduce_mean')
print('tf.reduce_all')
print('tf.reduce_any')
print('tf.count_nonzero')
print('tf.eisum')

print('tf.cumsum')
print('tf.cumprod')
print('tf.segment_sum')
print('tf.segment_prod')
print('tf.segment_max')
print('tf.segment_mean')
print('tf.unsorted_segment_sum')
print('tf.argmax')
print('tf.argmin')
print('tf.setduff1d')
print('tf.where')
print('tf.unique')
print('tf.SparseTensor')
print('tf.edit_distance')
